using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ObjetivaScripts.Bat_Files
{
    internal class DeleteDLLECF
    {
        public static string comando = @"
@ECHO OFF

ECHO.
ECHO    ##############################
ECHO    # APAGANDO DLLs DARUMA       #
ECHO    ##############################
ECHO.
DEL C:\WINDOWS\SYSTEM32\FS_345.DLL
DEL C:\WINDOWS\SYSTEM32\DARUMA32.DLL

DEL C:\WINDOWS\SYSTEM\FS_345.DLL
DEL C:\WINDOWS\SYSTEM\DARUMA32.DLL

DEL C:\WINDOWS\SYSWOW64\FS_345.DLL
DEL C:\WINDOWS\SYSWOW64\DARUMA32.DLL


ECHO.
ECHO    ##############################
ECHO    # APAGANDO DLLs BEMATECH     #
ECHO    ##############################
ECHO.
DEL C:\WINDOWS\SYSTEM32\BEMAFI32.DLL
DEL C:\WINDOWS\SYSTEM32\BEMAFI32.INI
DEL C:\WINDOWS\SYSTEM32\BEMAMFD.DLL
DEL C:\WINDOWS\SYSTEM32\BEMAMFD2.DLL
DEL C:\WINDOWS\SYSTEM32\AX6R32.DLL
DEL C:\WINDOWS\SYSTEM32\BEMAMFD2_MP4000THFI.DLL
DEL C:\WINDOWS\SYSTEM32\BEMATECH.DLL
DEL C:\WINDOWS\SYSTEM32\DAO350.DLL
DEL C:\WINDOWS\SYSTEM32\LIBEAY32.DLL
DEL C:\WINDOWS\SYSTEM32\MSJET35.DLL
DEL C:\WINDOWS\SYSTEM32\SIGN_BEMA.DLL
DEL C:\WINDOWS\SYSTEM32\REGISTRA.DLL

DEL C:\WINDOWS\SYSTEM\BEMAFI32.DLL
DEL C:\WINDOWS\SYSTEM\BEMAFI32.INI
DEL C:\WINDOWS\SYSTEM\BEMAMFD.DLL
DEL C:\WINDOWS\SYSTEM\BEMAMFD2.DLL
DEL C:\WINDOWS\SYSTEM\AX6R32.DLL
DEL C:\WINDOWS\SYSTEM\BEMAMFD2_MP4000THFI.DLL
DEL C:\WINDOWS\SYSTEM\BEMATECH.DLL
DEL C:\WINDOWS\SYSTEM\DAO350.DLL
DEL C:\WINDOWS\SYSTEM\LIBEAY32.DLL
DEL C:\WINDOWS\SYSTEM\MSJET35.DLL
DEL C:\WINDOWS\SYSTEM\SIGN_BEMA.DLL
DEL C:\WINDOWS\SYSTEM\REGISTRA.DLL

DEL C:\WINDOWS\SYSWOW64\BEMAFI32.DLL
DEL C:\WINDOWS\SYSWOW64\BEMAFI32.INI
DEL C:\WINDOWS\SYSWOW64\BEMAMFD.DLL
DEL C:\WINDOWS\SYSWOW64\BEMAMFD2.DLL
DEL C:\WINDOWS\SYSWOW64\AX6R32.DLL
DEL C:\WINDOWS\SYSWOW64\BEMAMFD2_MP4000THFI.DLL
DEL C:\WINDOWS\SYSWOW64\BEMATECH.DLL
DEL C:\WINDOWS\SYSWOW64\DAO350.DLL
DEL C:\WINDOWS\SYSWOW64\LIBEAY32.DLL
DEL C:\WINDOWS\SYSWOW64\MSJET35.DLL
DEL C:\WINDOWS\SYSWOW64\SIGN_BEMA.DLL
DEL C:\WINDOWS\SYSWOW64\REGISTRA.DLL

ECHO.
ECHO    ##############################
ECHO    # APAGANDO DLLs SWEDA        #
ECHO    ##############################
ECHO.
DEL C:\WINDOWS\SYSTEM32\swmfd.DLL
DEL C:\WINDOWS\SYSTEM32\CONVECF.DLL
DEL C:\WINDOWS\SYSTEM32\RSA.BIN

DEL C:\WINDOWS\SYSTEM\swmfd.DLL
DEL C:\WINDOWS\SYSTEM\CONVECF.DLL
DEL C:\WINDOWS\SYSTEM\RSA.BIN

DEL C:\WINDOWS\SYSWOW64\swmfd.DLL
DEL C:\WINDOWS\SYSWOW64\CONVECF.DLL
DEL C:\WINDOWS\SYSWOW64\RSA.BIN

ECHO.
ECHO    ##############################
ECHO    # APAGANDO DLLs DATAREGIS    #
ECHO    ##############################
ECHO.
DEL C:\WINDOWS\SYSTEM32\DLLG2.DLL
DEL C:\WINDOWS\SYSTEM32\DLLG2_GERADOR.DLL

DEL C:\WINDOWS\SYSTEM\DLLG2.DLL
DEL C:\WINDOWS\SYSTEM\DLLG2_GERADOR.DLL

DEL C:\WINDOWS\SYSWOW64\DLLG2.DLL
DEL C:\WINDOWS\SYSWOW64\DLLG2_GERADOR.DLL

ECHO.
ECHO    ##############################
ECHO    # APAGANDO DLLs ELGIN        #
ECHO    ##############################
ECHO.
DEL C:\WINDOWS\SYSTEM32\ELGIN.DLL
DEL C:\WINDOWS\SYSTEM32\ELGIN.INI

DEL C:\WINDOWS\SYSTEM\ELGIN.DLL
DEL C:\WINDOWS\SYSTEM\ELGIN.INI

DEL C:\WINDOWS\SYSWOW64\ELGIN.DLL
DEL C:\WINDOWS\SYSWOW64\ELGIN.INI


ECHO.
ECHO    ##############################
ECHO    # APAGANDO DLLs EPSON        #
ECHO    ##############################
ECHO.
DEL C:\WINDOWS\SYSTEM32\INTERFACEEPSON.DLL

DEL C:\WINDOWS\SYSTEM\INTERFACEEPSON.DLL

DEL C:\WINDOWS\SYSWOW64\INTERFACEEPSON.DLL

ECHO.
ECHO    ############################################
ECHO    #                                          #
ECHO    #  PRESSIONE QUALQUER TECLA PARA TERMINAR  #
ECHO    #                                          #
ECHO    #                  F I M                   #
ECHO    #                                          #
ECHO    ############################################
ECHO.
PAUSE >NUL
EXIT
";
    }
}
